nguage: cpp
sudo: required
dist: trusty
compiler:
- g++
os:
 - linux
install:
- sudo apt-get install cmake
- sudo apt-get install libgcrypt-dev
env:
- BUILD_TYPE=debug
- BUILD_TYPE=release
script:
- ./build.sh
